name: CI - Type Checking and ESLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # コードを取得
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 依存関係のインストール
      - name: Install dependencies
        run: bun install

      # TypeScript の型チェック
      - name: Run TypeScript type checking
        run: bun tsc --noEmit

      # ESLint の静的解析
      - name: Run ESLint
        run: bun eslint .
