name: ESLint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # コードを取得
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Bun をインストール
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo 'BUN_INSTALL=$HOME/.bun' >> $GITHUB_ENV
          echo 'PATH=$BUN_INSTALL/bin:$PATH' >> $GITHUB_ENV
          source ~/.bashrc
          export BUN_INSTALL=$HOME/.bun
          export PATH=$BUN_INSTALL/bin:$PATH

      # Bun のバージョン確認（デバッグ用）
      - name: Verify Bun installation
        run: |
          echo "Bun version:"
          bun --version

      # 依存関係をインストール
      - name: Install dependencies
        run: |
          source $GITHUB_ENV
          bun install

      # ESLint 静的解析
      - name: Run ESLint
        run: |
          source $GITHUB_ENV
          bun eslint .
