name: TypeScript Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      # コードを取得
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Bun をインストール
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo 'export BUN_INSTALL="$HOME/.bun"' >> $GITHUB_ENV
          echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> $GITHUB_ENV

      # 環境変数を適用
      - name: Load Bun into PATH
        run: source $GITHUB_ENV

      # 依存関係をインストール
      - name: Install dependencies
        run: bun install

      # TypeScript 型チェック
      - name: Run TypeScript type checking
        run: bun tsc --noEmit
