name: TypeScript Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      # コードを取得
      - name: Checkout code
        uses: actions/checkout@v3

      # Node.js のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Bun をインストール
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo 'export BUN_INSTALL=$HOME/.bun' >> $GITHUB_ENV
          echo 'export PATH=$HOME/.bun/bin:$PATH' >> $GITHUB_ENV

      # 環境変数をロード
      - name: Load Bun environment
        shell: bash
        run: |
          source ~/.bashrc
          export PATH=$HOME/.bun/bin:$PATH
          echo "PATH after sourcing .bashrc:"
          echo $PATH

      # Bun のバージョン確認
      - name: Verify Bun installation
        run: |
          source $GITHUB_ENV
          bun --version

      # 依存関係をインストール
      - name: Install dependencies
        run: |
          source $GITHUB_ENV
          bun install

      # TypeScript 型チェック
      - name: Run TypeScript type checking
        run: |
          source $GITHUB_ENV
          bun tsc --noEmit
